### ISSUE TITLE
[Bug] The popup after submitting the email on the forgot password is wrong

### ISSUE THREAD

**Issue by suho** [congtung10t2/NimbleTest#42]
## Issue

It's good that you've implemented the forgot password feature. However, the UI is different from the design.

<img width="894" alt="image" src="https://github.com/congtung10t2/NimbleTest/assets/19943832/5ab072f4-def3-499f-bdbe-1318868b9450">

## Expected
After pressing the reset button, we should show the top popup button like the design.

## Steps to reproduce
1. Open the app
2. Press on the `Forgot?` button
3. Check the alert

**Comment by congtung10t2** [comment]
message return from BE is difference from message in figma. because we have inconsistency design vs BE that's why I just focus on feature instead of UI.

**Comment by congtung10t2** [comment]
basically every BE message should follow design right?

**Comment by suho** [comment]
@congtung10t2 We can ignore the message from the backend in this case and show the popup like the design when we successfully reset the password
